version: '3.3'
services:
  web:
    build:
      context: ./php
      dockerfile: dockerfile
    container_name: php73
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: mydb
       MYSQL_USER: user
       MYSQL_PASSWORD: user
    volumes:
      - ./php:/docker-entrypoint-phpdb.data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    # volumes:
    # - ./docker/mysql/data:/var/lib/mysql:rw
    # - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
#    db:    
#     image: mysql:8
#     container_name: db
#     environment:
#       MYSQL_ROOT_PASSWORD: my_secret_password
#       MYSQL_DATABASE: app_db
#       MYSQL_USER: db_user
#       MYSQL_PASSWORD: db_user_pass
#     ports:
#       - "3306:3306"
#     volumes:
#       - dbdata:/var/lib/mysql
#       - ./scripts/credentials.sql:/docker-entrypoint-initdb.d/login.sql
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: pma
#     links:
#       - db
#     environment:
#       PMA_HOST: db
#       PMA_PORT: 3306
#       PMA_ARBITRARY: 1
#     restart: always
#     ports:
#       - 8081:80
# volumes:
#   dbdata:
  #dockerfile:
    #build: Dockerfile/.
    #command: /bin/sh -c "entrypoint.sh"
   
#    image: mysql:8.0
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: credentials
#      MYSQL_USER: devuser
#      MYSQL_PASSWORD: devpass
#    ports:
#     - 6033:3306
#    expose:
#     - 3306
#    volumes:
#     - ./scripts/credentials.sql:/docker-entrypoint-initdb.d/login.sql
#volumes:
#  my-db:
